package com.yessorae.domain.usecase

import com.yessorae.domain.model.parameter.Prompt
import com.yessorae.domain.model.parameter.createNegative
import com.yessorae.domain.model.parameter.createPositive
import com.yessorae.domain.repository.PreferenceRepository
import com.yessorae.domain.repository.PromptRepository
import javax.inject.Inject

class InsertInitialPromptUseCase @Inject constructor(
    private val promptRepository: PromptRepository,
    private val preferenceRepository: PreferenceRepository
) {
    suspend operator fun invoke() {
        if (preferenceRepository.getCompleteInitPromptData().not()) {
            promptRepository.insertPrompts(positivePrompt + negativePrompt)
            preferenceRepository.setCompleteInitPromptData()
        }
    }

    /**
     * [civitai 프롬프트 통계](https://rentry.org/toptokens#20-most-common-samplers) 에 기반한 프롬프트 셋
     * 긍정 및 부정 각각 1~100위씩 미리 세팅해준다.
     * 주석처리 된 프롬프트는 19금이거나 화질관련 또는 중복이 심하거나 너무 쓸데없어 보이는 경우.
     */
    private val positivePrompt = listOf(
        Prompt.createPositive(prompt = "masterpiece"),
        Prompt.createPositive(prompt = "best quality"),
        Prompt.createPositive(prompt = "1girl"),
        Prompt.createPositive(prompt = "solo"),
        Prompt.createPositive(prompt = "looking at viewer"),
        Prompt.createPositive(prompt = "realistic"),
        Prompt.createPositive(prompt = "sharp focus"),
        Prompt.createPositive(prompt = "photorealistic"),
        Prompt.createPositive(prompt = "long hair"),
        Prompt.createPositive(prompt = "smile"),
        Prompt.createPositive(prompt = "full body"),
        Prompt.createPositive(prompt = "highres"),
        Prompt.createPositive(prompt = "highly detailed"),
        Prompt.createPositive(prompt = "ultra-detailed"),
        Prompt.createPositive(prompt = "intricate"), // 뒤얽힌
        Prompt.createPositive(prompt = "illustration"),
        Prompt.createPositive(prompt = "standing"),
        Prompt.createPositive(prompt = "blush"),
        Prompt.createPositive(prompt = "cinematic lighting"),
        Prompt.createPositive(prompt = "bangs"),
        Prompt.createPositive(prompt = "hdr"),
        Prompt.createPositive(prompt = "intricate details"),
        Prompt.createPositive(prompt = "depth of field"),
        Prompt.createPositive(prompt = "extremely detailed"),
        Prompt.createPositive(prompt = "hdr"),
        Prompt.createPositive(prompt = "depth of field"),
        Prompt.createPositive(prompt = "intricate details"),
        Prompt.createPositive(prompt = "extremely detailed"),
        Prompt.createPositive(prompt = "absurdres"),
        Prompt.createPositive(prompt = "high quality"),
        Prompt.createPositive(prompt = "upper body"),
        Prompt.createPositive(prompt = "raw photo"),
        Prompt.createPositive(prompt = "detailed eyes"),
        Prompt.createPositive(prompt = "short hair"),
        Prompt.createPositive(prompt = "black hair"),
        Prompt.createPositive(prompt = "detailed face"),
        Prompt.createPositive(prompt = "outdoors"),
        Prompt.createPositive(prompt = "detailed"),
        Prompt.createPositive(prompt = "ultra high res"),
        Prompt.createPositive(prompt = "trending on artstation"),
        Prompt.createPositive(prompt = "portrait"),
        Prompt.createPositive(prompt = "jewelry"),
        Prompt.createPositive(prompt = "cowboy shot"),
        Prompt.createPositive(prompt = "night"),
        Prompt.createPositive(prompt = "beautiful face"),
        Prompt.createPositive(prompt = "shiny skin"),
        Prompt.createPositive(prompt = "1boy"),
        Prompt.createPositive(prompt = "soft lighting"),
        Prompt.createPositive(prompt = "film grain"),
        Prompt.createPositive(prompt = "perfect face"),
        Prompt.createPositive(prompt = "blonde hair"),
        Prompt.createPositive(prompt = "white hair"),
        Prompt.createPositive(prompt = "red eyes"),
        Prompt.createPositive(prompt = "sitting"),
        Prompt.createPositive(prompt = "hair ornament"),
        Prompt.createPositive(prompt = "beautiful"),
        Prompt.createPositive(prompt = "beautiful detailed eyes"),
        Prompt.createPositive(prompt = "cute"),
        Prompt.createPositive(prompt = "earrings"),
        Prompt.createPositive(prompt = "dramatic"),
        Prompt.createPositive(prompt = "navel"), // 배꼽
        Prompt.createPositive(prompt = "open mouth"),
        Prompt.createPositive(prompt = "volumetric lighting"),
        Prompt.createPositive(prompt = "closed mouth"),
        Prompt.createPositive(prompt = "highest quality"),
        Prompt.createPositive(prompt = "photo-realistic"),
        Prompt.createPositive(prompt = "bokeh"), // 뭉개진 빛들
        Prompt.createPositive(prompt = "bare shoulders"),
        Prompt.createPositive(prompt = "ultra detailed"),
        Prompt.createPositive(prompt = "artstation"),
        Prompt.createPositive(prompt = "brown hair"),
        Prompt.createPositive(prompt = "dress"),
        Prompt.createPositive(prompt = "1 girl"),
        Prompt.createPositive(prompt = "huge breasts"),
        Prompt.createPositive(prompt = "concept art"),
        Prompt.createPositive(prompt = "cinematic"),
        Prompt.createPositive(prompt = "green eyes"),
        Prompt.createPositive(prompt = "indoors"),
        Prompt.createPositive(prompt = "8k uhd"),
        Prompt.createPositive(prompt = "gloves"),
        Prompt.createPositive(prompt = "official art"),
        Prompt.createPositive(prompt = "thighhighs"),
        Prompt.createPositive(prompt = "simple background"),
        Prompt.createPositive(prompt = "detailed background"),
        Prompt.createPositive(prompt = "skirt"),
        Prompt.createPositive(prompt = "smiling"),
        Prompt.createPositive(prompt = "smooth"),
        Prompt.createPositive(prompt = "long_hair"),
        Prompt.createPositive(prompt = "very long hair"),
        Prompt.createPositive(prompt = "shirt"),
        Prompt.createPositive(prompt = "perfect lighting"),
        Prompt.createPositive(prompt = "amazing"),
        Prompt.createPositive(prompt = "long sleeves"),
        Prompt.createPositive(prompt = "dynamic pose"),
        Prompt.createPositive(prompt = "fantasy"),
        Prompt.createPositive(prompt = "dslr"),
        Prompt.createPositive(prompt = "mature female"),
        Prompt.createPositive(prompt = "choker"),
        Prompt.createPositive(prompt = "digital painting"),
        Prompt.createPositive(prompt = "intricate detail"),
        Prompt.createPositive(prompt = "modelshoot style"),
        Prompt.createPositive(prompt = "collarbone")
//                PromptOption.createPositive(prompt = "8k"),
//                PromptOption.createPositive(prompt = "nsfw"),
//                PromptOption.createPositive(prompt = "breasts"),
//                PromptOption.createPositive(prompt = "large breasts"),
//                PromptOption.createPositive(prompt = "absurdres"),
//                PromptOption.createPositive(prompt = "4k"),
//                PromptOption.createPositive(prompt = "blue eyes"),
//                PromptOption.createPositive(prompt = "extremely detailed cg unity 8k wallpaper"),
//                PromptOption.createPositive(prompt = "cleavage"),
//                PromptOption.createPositive(prompt = "medium breasts"),
//                PromptOption.createPositive(prompt = "small breasts"),
//                PromptOption.createPositive(prompt = "nipples"),
//                PromptOption.createPositive(prompt = "pussy"),
//                PromptOption.createPositive(prompt = "sexy"),
//                PromptOption.createPositive(prompt = "looking_at_viewer"),
    )

    private val negativePrompt = listOf(
        Prompt.createNegative(prompt = "low quality"),
        Prompt.createNegative(prompt = "blurry"),
        Prompt.createNegative(prompt = "bad anatomy"),
        Prompt.createNegative(prompt = "worst quality"),
        Prompt.createNegative(prompt = "text"),
        Prompt.createNegative(prompt = "watermark"),
        Prompt.createNegative(prompt = "normal quality"),
        Prompt.createNegative(prompt = "ugly"),
        Prompt.createNegative(prompt = "signature"),
        Prompt.createNegative(prompt = "lowres"),
        Prompt.createNegative(prompt = "deformed"),
        Prompt.createNegative(prompt = "extra limbs"),
        Prompt.createNegative(prompt = "disfigured"),
        Prompt.createNegative(prompt = "cropped"),
        Prompt.createNegative(prompt = "jpeg artifacts"),
        Prompt.createNegative(prompt = "bad hands"),
        Prompt.createNegative(prompt = "error"),
        Prompt.createNegative(prompt = "mutation"),
        Prompt.createNegative(prompt = "missing fingers"),
        Prompt.createNegative(prompt = "username"),
        Prompt.createNegative(prompt = "poorly drawn hands"),
        Prompt.createNegative(prompt = "poorly drawn face"),
        Prompt.createNegative(prompt = "monochrome"),
        Prompt.createNegative(prompt = "extra digit"),
        Prompt.createNegative(prompt = "fewer digits"),
        Prompt.createNegative(prompt = "out of frame"),
        Prompt.createNegative(prompt = "extra fingers"),
        Prompt.createNegative(prompt = "mutated hands"),
        Prompt.createNegative(prompt = "extra legs"),
        Prompt.createNegative(prompt = "extra arms"),
        Prompt.createNegative(prompt = "bad proportions"),
        Prompt.createNegative(prompt = "long neck"),
        Prompt.createNegative(prompt = "fused fingers"),
        Prompt.createNegative(prompt = "missing arms"),
        Prompt.createNegative(prompt = "duplicate"),
        Prompt.createNegative(prompt = "mutated"),
        Prompt.createNegative(prompt = "missing legs"),
        Prompt.createNegative(prompt = "too many fingers"),
        Prompt.createNegative(prompt = "mutilated"),
        Prompt.createNegative(prompt = "malformed limbs"),
        Prompt.createNegative(prompt = "3d"),
        Prompt.createNegative(prompt = "artist name"),
        Prompt.createNegative(prompt = "gross proportions"),
        Prompt.createNegative(prompt = "cloned face"),
        Prompt.createNegative(prompt = "morbid"),
        Prompt.createNegative(prompt = "bad art"),
        Prompt.createNegative(prompt = "cartoon"),
        Prompt.createNegative(prompt = "grayscale"),
        Prompt.createNegative(prompt = "logo"),
        Prompt.createNegative(prompt = "nsfw"),
        Prompt.createNegative(prompt = "poorly drawn"),
        Prompt.createNegative(prompt = "sketches"),
        Prompt.createNegative(prompt = "skin blemishes"),
        Prompt.createNegative(prompt = "skin spots"),
        Prompt.createNegative(prompt = "censored"),
        Prompt.createNegative(prompt = "acnes"),
        Prompt.createNegative(prompt = "close up"),
        Prompt.createNegative(prompt = "mutated hands and fingers"),
        Prompt.createNegative(prompt = "malformed hands"),
        Prompt.createNegative(prompt = "long body"),
        Prompt.createNegative(prompt = "child"),
        Prompt.createNegative(prompt = "paintings"),
        Prompt.createNegative(prompt = "missing limb"),
        Prompt.createNegative(prompt = "loli"),
        Prompt.createNegative(prompt = "age spot"),
        Prompt.createNegative(prompt = "extra limb"),
        Prompt.createNegative(prompt = "fat"),
        Prompt.createNegative(prompt = "bad feet"),
        Prompt.createNegative(prompt = "anime"),
        Prompt.createNegative(prompt = "b&w"),
        Prompt.createNegative(prompt = "sketch"),
        Prompt.createNegative(prompt = "greyscale"),
        Prompt.createNegative(prompt = "floating limbs"),
        Prompt.createNegative(prompt = "disconnected limbs"),
        Prompt.createNegative(prompt = "poorly drawn feet"),
        Prompt.createNegative(prompt = "tiling"),
        Prompt.createNegative(prompt = "body out of frame"),
        Prompt.createNegative(prompt = "glans"),
        Prompt.createNegative(prompt = "out of focus"),
        Prompt.createNegative(prompt = "3d render"),
        Prompt.createNegative(prompt = "cross-eye"),
        Prompt.createNegative(prompt = "disgusting"),
        Prompt.createNegative(prompt = "drawing"),
        Prompt.createNegative(prompt = "bad body"),
        Prompt.createNegative(prompt = "multiple views"),
        Prompt.createNegative(prompt = "malformed"),
        Prompt.createNegative(prompt = "nude"),
        Prompt.createNegative(prompt = "photoshop"),
        Prompt.createNegative(prompt = "simple background"),
        Prompt.createNegative(prompt = "video game"),
        Prompt.createNegative(prompt = "oversaturated"),
        Prompt.createNegative(prompt = "futa"),
        Prompt.createNegative(prompt = "fewer fingers"),
        Prompt.createNegative(prompt = "pubic hair"),
        Prompt.createNegative(prompt = "depth of field"),
        Prompt.createNegative(prompt = "black and white"),
        Prompt.createNegative(prompt = "painting"),
        Prompt.createNegative(prompt = "extra digits"),
        Prompt.createNegative(prompt = "render"),
        Prompt.createNegative(prompt = "old"),
        Prompt.createNegative(prompt = "nipples"),
        Prompt.createNegative(prompt = "extra hands"),
        Prompt.createNegative(prompt = "more than 2 nipples")
//                PromptOption.createNegative(prompt = "easynegative"), // embeddings 이름
//                PromptOption.createNegative(prompt = "bad_prompt_version2"),
//                PromptOption.createNegative(prompt = "bad-hands-5"),
//                PromptOption.createNegative(prompt = "ng_deepnegative_v1_75t"),
//                PromptOption.createNegative(prompt = "bad_prompt"),
//                PromptOption.createNegative(prompt = "bad-artist"),
    )
}